package com.ouken.phone.app.oukenstudioapp.assets;

public class SkinNames {
	
	private SkinNames() {}
	
	public static final String
	PIXEL_REGION = "pxl",
	PANE_DRAWABLE_LIGHT_GRAY = "pd0",
	PANE_DRAWABLE_GRAY = "pd1",
	PANE_DRAWABLE_DARK_GRAY = "pd2",
	PANE_DRAWABLE_DARKEST_GRAY = "pd3",
	
	LABEL_STYLE_10 = "ls10",
	LABEL_STYLE_12 = "ls12",
	
	IMAGE_TEXT_BUTTON_STYLE_DARKEST_GRAY10 = "itbsdstg10",
	IMAGE_TEXT_BUTTON_STYLE_DARKEST_GRAY12 = "itbsdstg12",
	IMAGE_TEXT_BUTTON_STYLE_DARK_GRAY10 = "itbsdg10",
	IMAGE_TEXT_BUTTON_STYLE_DARK_GRAY12 = "itbsdg12",
	IMAGE_TEXT_BUTTON_STYLE_GRAY10 = "itbsg10",
	IMAGE_TEXT_BUTTON_STYLE_GRAY12 = "itbsg12",
	
	SCROLL_PANE_STYLE = "scps",
	SPLIT_PANE_STYLE = "spps",
	TEXT_FIELD_STYLE10 = "tfs10",
	TEXT_FIELD_STYLE12 = "tfs12",
	
	LIST_STYLE_GRAY_10 = "listsg10",
	LIST_STYLE_GRAY_12 = "listsg12",
	LIST_STYLE_DARK_GRAY_10 = "listsdg10",
	LIST_STYLE_DARK_GRAY_12 = "listsdg12",
	
	SELECT_BOX_STYLE_DARK_GRAY_10 = "selboxdg10",
	SELECT_BOX_STYLE_DARK_GRAY_12 = "selboxdg12",
	
	SELECT_BOX_STYLE_GRAY_10 = "selboxg10",
	SELECT_BOX_STYLE_GRAY_12 = "selboxg12",
	
	CHECK_BOX_STYLE = "checkboxstyle",
	
	TREE_STYLE= "trstl",
	
	PLUS_MINUS_BUTTON_STYLE_DARK_GRAY ="pmbstdg",
	PLUS_MINUS_BUTTON_STYLE_LIGHT_GRAY ="pmbstlg",
	PLUS_MINUS_BUTTON_STYLE_GRAY ="pmbstg",
	SELECTION_BUTTON_STYLE_DARKEST_GRAY = "selb",
	PRESSED_BUTTON_STYLE_DARKEST_GRAY = "preb";
	
}
